### ISSUE TITLE
几点修改建议

### ISSUE THREAD

**Issue by filow** [mShining/web_tasks#1]
1. 如果想在字符串中拼接一个变量，可以直接用"something #{somevar} another"来输出
2. 局部变量的名字不够有意义
3. 考虑使用矩阵乘法来加速运算，see: http://www.cnblogs.com/xudong-bupt/archive/2013/03/19/2966954.html

检查点评分：
A --- 1. github上存在相应项目目录并且结构正确
A --- 2. fib.rb文件在运行时会首先让用户输入一个1-100之间的数字n，然后他会输出一个1-n的斐波那契数列

额外加分项：
1. commit 频繁且提交信息有意义

**Comment by mShining** [comment]
收到！

**Comment by filow** [comment]
回归评测：
由于你对矩阵乘法还不是很了解，所以暂时不做要求。不过接下来可以在有空的时候好好去了解一下。
其他地方有所改正，不过总的来说你的代码写得还是不太过关，以后好好加油吧。
评分： B

总评： B

**Comment by mShining** [comment]
嗯好！
