### ISSUE TITLE
B1评价及修改建议

### ISSUE THREAD

**Issue by filow** [mShining/web_tasks#2]
## 修改建议
1. 推荐使用JSON或者YAML来序列化对象，自己构造一个格式存入txt比较容易出现问题，存储也不是很灵活
2. Operation#add中，推荐将写文件的操作放入Message类中，因为这个实际上是对message对象状态的保存
3. Opertion的每次操作都需要重新打开文件，这样效率太低了。推荐去实例化一个 UniversalProperty，然后之后的所有操作都在这个实例中完成。在对其属性做更改后，需要这个类自动的去保存最新的状态。不要把保存状态的代码放在Operation里，这个应该让UniversalProperty自己来做。这就是类的封装性
4. 167行，不需要刷新，直接跳转到'/'即可
5. reverse方法调用的有点多，看看能不能优化一下
6. 搜索的内容是空值时，应该返回全部列表
7. 作者搜索最好可以模糊匹配
8. 列表页要显示id，不然怎么按照id查找呢？
9. 只能删除最新的记录？这个不合理。另外，要考虑id可能不连续的情况。
10. 留言的内容合法校验也应该放在Message类中

总的来说，Message类你没有用上，Operation类掺杂了太多东西不纯粹，希望都能改一下。
星期六晚上8点前要修改完成。
## 评分

B -- 1. get / 时，可以看到留言列表和筛选表单，留言列表按照倒序排序，且每条留言后有一个删除按钮
A -- 2. 通过输入筛选条件，可以正确筛选出所需的条目
B -- 3. 点击删除按钮时，可以正确删除
A -- 4. 当用户提交无效的信息时，会提示用户出错信息。这里需要对所有可能的用户提交内容做验证。
B -- 5. 建立了一个类来管理有关留言内容的操作，且结构满足规范
B -- 6. 留言类的每一个方法都能考虑到各种的输入情况，能正确的返回数据或错误信息

**Comment by mShining** [comment]
更新：
1.已使用YAML来序列化对象。
2.Message类中已包含load、add等函数。
3.首页列表已显示ID，且按倒序排列。
4.已实现作者查询和日期查询中的模糊搜索功能。
5.可以选择删除任意一条留言，留言按钮在每条留言右下方。
6.查询逻辑修改为查询为空时返回所有留言。

**Comment by filow** [comment]
感觉你没有领会我的意思。我是希望你写两个类，一个是Message类，负责留言信息的存储和校验（在初始化的时候就去校验，如果不通过抛出异常），另一个类是MessageManager类，这个类负责管理多个Message对象，add, delete, edit等操作都在里面，而且这些方法都是实例方法，不是类方法。
现在你的问题在于把这两个类的职能混淆到一块儿去了，会造成整个逻辑的混乱。
而且在app中直接读取文件然后赋值的做法也不是很好，这个工作应该交给MessageManager来做。app.rb中只需要给这个类传入一个路径参数就可以了。

主要再改改这个地方就可以了。

**Comment by filow** [comment]
做的还算凑活，好像也没有看过我写的示例，以后有空可以参考一下。
回归评测： B
总评： B
